export const FETCH_FOOTBALL_LIVE = 'FETCH_FOOTBALL_LIVE';
export const FETCH_EVENT = 'FETCH_EVENT';
export const CHANGE_UNIT = 'CHANGE_UNIT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const SOCKET_PRICE_CHANGE='SOCKET_PRICE_CHANGE';
export const SOCKET_OUTCOME_STATUS = 'SOCKET_OUTCOME_STATUS';